apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sample-worker
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: sample-worker
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
