apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-api
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stable-api
  template:
    metadata:
      labels:
        app: stable-api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: public.ecr.aws/nginx/nginx:1.25.4
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: stable-api
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: stable-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stable-api
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/stable-api-role
