apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: istio-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      containers:
        - name: curl
          image: curlimages/curl:8.11.1
          command: ["sleep", "365d"]
