# Sample values for istio/gateway.
# For EKS, add AWS Load Balancer annotations if needed.
service:
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
