# Development example for this wrapper chart.
# Do not use this file unchanged in production.

keycloak:
  image:
    registry: docker.io
    repository: bitnami/keycloak
    tag: 26.3.3-debian-12-r0

  auth:
    adminUser: "{{KEYCLOAK_ADMIN_USER}}"
    adminPassword: "{{KEYCLOAK_ADMIN_PASSWORD}}"

  production: false

  postgresql:
    enabled: true
    auth:
      username: "{{DEV_DB_USER}}"
      password: "{{DEV_DB_PASSWORD}}"
      database: "{{DEV_DB_NAME}}"

  ingress:
    enabled: false

  replicaCount: 1

  resourcesPreset: "small"

  metrics:
    enabled: true
